apiVersion: v1
kind: Service
metadata: 
  namespace: log
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
      app: elasticsearch
  ports:
    - port: 9200
      name: rest
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  namespace: log
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:8.1.3
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
          - containerPort: 9200
            name: rest
            protocol: TCP
        env:
          - name: cluster.name
            value: k8s-logs
          - name: xpack.security.enabled
            value: "false"
          - name: discovery.type
            value: "single-node"
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"