apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: log
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: wellslin/k8s:latest
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          ports:
            - containerPort: 80
        - name: fluent
          image: wellslin/fluent:latest
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          ports:
            - containerPort: 24224
              protocol: UDP
            - containerPort: 24224